openapi: 3.0.0
info:
  title: HTTP Request Tester API by FUMEA
  version: 1.0.0
  description: API to test different HTTP methods and status codes


paths:
  /testGet:
    get:
      summary: Test GET request
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating the success of the request.
      externalDocs:
        url: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET

  /testPost:
    post:
      summary: Test POST request
      responses:
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating the success of the request.
      externalDocs:
        url: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST

  /testPut:
    put:
      summary: Test PUT request
      responses:
        '204':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating the success of the request.
      externalDocs:
        url: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT

  /testPatch:
    patch:
      summary: Test PATCH request
      responses:
        '304':
          description: Not Modified
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating that the resource has not been modified.
      externalDocs:
        url: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH

  /testDelete:
    delete:
      summary: Test DELETE request
      responses:
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating that the request was malformed.
      externalDocs:
        url: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

  /test401:
    get:
      summary: Test 401 Unauthorized
      responses:
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating that the request was unauthorized.
      externalDocs:
        url: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

  /test403:
    get:
      summary: Test 403 Forbidden
      responses:
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating that the request was forbidden.
      externalDocs:
        url: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

  /test404:
    get:
      summary: Test 404 Not Found
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating that the requested resource could not be found.
      externalDocs:
        url: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

  /test405:
    get:
      summary: Test 405 Method Not Allowed
      responses:
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating that the request method is not allowed for the requested resource.
      externalDocs:
        url: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

  /test418:
    get:
      summary: Test 418 I’m a teapot
      responses:
        '418':
          description: I’m a teapot
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A message indicating that the server is a teapot.
      externalDocs:
        url: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418





                    
# __  __           _        ____          _____                    
#|  \/  | __ _  __| | ___  | __ ) _   _  |  ___|   _ _ __ ___   ___  __ _ 
#| |\/| |/ _` |/ _` |/ _ \ |  _ \| | | | | |_ | | | | '_ ` _ \ / _ \/ _` |
#| |  | | (_| | (_| |  __/ | |_) | |_| | |  _|| |_| | | | | | |  __/ (_| |
#|_|  |_|\__,_|\__,_|\___| |____/ \__, | |_|   \__,_|_| |_| |_|\___|\__,_|
#                                 |___/                                   